require.context('../images', true)

import '../src/materialdesignicons.min.css'
import '../src/vendor.bundle.base.css'
import '../src/jquery-jvectormap.css'
// import '../src/flag-icon.min.css'
import '../src/owl.carousel.min.css'
import '../src/owl.theme.default.min.css'
import '../src/css-stars.css'
import './application.css'
import '../src/dataTables.bootstrap4.css'
import '../src/select2.min.css'
import '../src/select2-bootstrap.min.css'
import '../javascripts/rails-ujs'
import '../javascripts/vendor.bundle.base'
import '../javascripts/Chart.min'
import '../javascripts/chart'
import '../javascripts/progressbar.min'
import '../javascripts/jquery-jvectormap.min'
import '../javascripts/jquery-jvectormap-world-mill-en'
import '../javascripts/owl.carousel.min'
import '../javascripts/off-canvas'
import '../javascripts/hoverable-collapse'
import '../javascripts/misc'
import '../javascripts/settings'
import '../javascripts/todolist'
// import '../javascripts/dashboard'
import '../javascripts/jquery.dataTables'
import '../javascripts/dataTables.bootstrap4'
import '../javascripts/jquery.steps.min'
import '../javascripts/sweetalert.min'
import '../javascripts/jquery.avgrund.min'
// import '../javascripts/alerts'
import '../javascripts/file-upload'
import '../javascripts/typeahead'
import '../javascripts/select2'
import '../javascripts/avgrund'
import '../javascripts/data-table'
import '../javascripts/paginate'
// import '../javascripts/wizard.js'
